// ModelMaster 官方油漆数据库 v1.2
// 收录：田宫 Tamiya / Mr.Color（含CL透明系列）/ 盖亚 Gaianotes（含EVO补土/SB金属）/ Finisher's
// 格式：{ brand, code, name, nameEn, hex, type, finish }
// finish: 'flat'=消光 'semi'=半光 'gloss'=光泽

const PAINT_DB = [

  // ─── 田宫 Tamiya X 系列（光泽/珐琅）───────────────────────────────────────
  { brand:'田宫 Tamiya', code:'X-1',  name:'黑色',    nameEn:'Black',          hex:'#1a1a1a', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-2',  name:'白色',    nameEn:'White',          hex:'#f5f5f5', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-3',  name:'皇家蓝',  nameEn:'Royal Blue',     hex:'#1a3a8c', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-4',  name:'蓝色',    nameEn:'Blue',           hex:'#1565c0', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-5',  name:'绿色',    nameEn:'Green',          hex:'#2e7d32', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-6',  name:'橙色',    nameEn:'Orange',         hex:'#e65100', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-7',  name:'红色',    nameEn:'Red',            hex:'#c62828', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-8',  name:'柠檬黄',  nameEn:'Lemon Yellow',   hex:'#f9e010', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-9',  name:'棕色',    nameEn:'Brown',          hex:'#6d4c41', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-10', name:'枪金属',  nameEn:'Gun Metal',      hex:'#546e7a', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-11', name:'铬银',    nameEn:'Chrome Silver',  hex:'#e0e0e0', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-12', name:'金色',    nameEn:'Gold Leaf',      hex:'#d4a017', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-13', name:'金属蓝',  nameEn:'Metallic Blue',  hex:'#1565c0', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-14', name:'天空蓝',  nameEn:'Sky Blue',       hex:'#4fc3f7', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-15', name:'浅绿',    nameEn:'Light Green',    hex:'#81c784', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-16', name:'紫色',    nameEn:'Purple',         hex:'#6a1b9a', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-17', name:'粉色',    nameEn:'Pink',           hex:'#f48fb1', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-18', name:'半光黑',  nameEn:'Semi Gloss Black',hex:'#212121',type:'珐琅漆', finish:'semi'  },
  { brand:'田宫 Tamiya', code:'X-19', name:'烟色',    nameEn:'Smoke',          hex:'#616161', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-20', name:'稀释剂',  nameEn:'Thinner',        hex:'#eeeeee', type:'工具',   finish:'none'  },
  { brand:'田宫 Tamiya', code:'X-21', name:'消光剂',  nameEn:'Flat Base',      hex:'#eeeeee', type:'工具',   finish:'none'  },
  { brand:'田宫 Tamiya', code:'X-22', name:'透明漆',  nameEn:'Clear',          hex:'#f0f8ff', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-23', name:'透明蓝',  nameEn:'Clear Blue',     hex:'#90caf9', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-24', name:'透明黄',  nameEn:'Clear Yellow',   hex:'#fff176', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-25', name:'透明绿',  nameEn:'Clear Green',    hex:'#a5d6a7', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-26', name:'透明橙',  nameEn:'Clear Orange',   hex:'#ffcc80', type:'珐琅漆', finish:'gloss' },
  { brand:'田宫 Tamiya', code:'X-27', name:'透明红',  nameEn:'Clear Red',      hex:'#ef9a9a', type:'珐琅漆', finish:'gloss' },

  // ─── 田宫 Tamiya XF 系列（消光/水性）────────────────────────────────────────
  { brand:'田宫 Tamiya', code:'XF-1',  name:'消光黑',   nameEn:'Flat Black',       hex:'#212121', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-2',  name:'消光白',   nameEn:'Flat White',       hex:'#f5f5f5', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-3',  name:'消光黄',   nameEn:'Flat Yellow',      hex:'#fdd835', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-4',  name:'黄绿',     nameEn:'Yellow Green',     hex:'#9ccc65', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-5',  name:'消光绿',   nameEn:'Flat Green',       hex:'#388e3c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-6',  name:'铜色',     nameEn:'Copper',           hex:'#b87333', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-7',  name:'消光红',   nameEn:'Flat Red',         hex:'#c62828', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-8',  name:'消光蓝',   nameEn:'Flat Blue',        hex:'#1565c0', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-9',  name:'船体红',   nameEn:'Hull Red',         hex:'#8b0000', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-10', name:'棕色',     nameEn:'Brown',            hex:'#6d4c41', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-11', name:'军绿',     nameEn:'J.N. Green',       hex:'#4e5b31', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-12', name:'J.N.灰',   nameEn:'J.N. Grey',        hex:'#90a4ae', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-13', name:'J.A.绿',   nameEn:'J.A. Green',       hex:'#558b2f', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-14', name:'J.A.灰',   nameEn:'J.A. Grey',        hex:'#78909c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-15', name:'消光肤色', nameEn:'Flat Flesh',       hex:'#ffcc80', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-16', name:'消光铝',   nameEn:'Flat Aluminium',   hex:'#bdbdbd', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-17', name:'海蓝',     nameEn:'Sea Blue',         hex:'#1976d2', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-18', name:'中等蓝',   nameEn:'Medium Blue',      hex:'#1e88e5', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-19', name:'天蓝',     nameEn:'Sky',              hex:'#81d4fa', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-20', name:'中等灰',   nameEn:'Medium Grey',      hex:'#9e9e9e', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-21', name:'天空',     nameEn:'Sky',              hex:'#b3e5fc', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-22', name:'RLM灰',    nameEn:'RLM Grey',         hex:'#bdbdbd', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-23', name:'浅蓝',     nameEn:'Light Blue',       hex:'#64b5f6', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-24', name:'暗灰',     nameEn:'Dark Grey',        hex:'#546e7a', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-25', name:'暗海灰',   nameEn:'Dark Sea Grey',    hex:'#607d8b', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-26', name:'暗绿',     nameEn:'Deep Green',       hex:'#2e7d32', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-27', name:'暗绿2',    nameEn:'Black Green',      hex:'#1b5e20', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-49', name:'消光卡其', nameEn:'Khaki',            hex:'#827717', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-50', name:'野战绿',   nameEn:'Field Green',      hex:'#558b2f', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-51', name:'卡其',     nameEn:'Khaki Drab',       hex:'#8d6e63', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-52', name:'消光土',   nameEn:'Flat Earth',       hex:'#795548', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-53', name:'中等土',   nameEn:'Neutral Grey',     hex:'#757575', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-54', name:'暗海蓝',   nameEn:'Dark Sea Blue',    hex:'#0d47a1', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-55', name:'甲板棕',   nameEn:'Deck Tan',         hex:'#bcaaa4', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-56', name:'金属灰',   nameEn:'Metallic Grey',    hex:'#90a4ae', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-57', name:'皮革棕',   nameEn:'Buff',             hex:'#a1887f', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-58', name:'橄榄绿',   nameEn:'Olive Green',      hex:'#689f38', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-59', name:'沙漠黄',   nameEn:'Desert Yellow',    hex:'#c8a84b', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-60', name:'暗黄',     nameEn:'Dark Yellow',      hex:'#b8860b', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-61', name:'暗绿3',    nameEn:'Dark Green',       hex:'#1b5e20', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-62', name:'橄榄土',   nameEn:'Olive Drab',       hex:'#6d6f30', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-63', name:'德国灰',   nameEn:'German Grey',      hex:'#424242', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-64', name:'红棕',     nameEn:'Red Brown',        hex:'#8d1c1c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-65', name:'野战灰',   nameEn:'Field Grey',       hex:'#78909c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-66', name:'光浅灰',   nameEn:'Light Grey',       hex:'#cfd8dc', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-67', name:'NATO绿',   nameEn:'NATO Green',       hex:'#4a5c28', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-68', name:'NATO棕',   nameEn:'NATO Brown',       hex:'#7b5e3f', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-69', name:'NATO黑',   nameEn:'NATO Black',       hex:'#2d2d2d', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-70', name:'中等棕',   nameEn:'Medium Brown',     hex:'#8d6e63', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-71', name:'驾驶舱色', nameEn:'Cockpit Color',    hex:'#5d8a5e', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-72', name:'JASDF棕',  nameEn:'JASDF Brown',      hex:'#795548', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-73', name:'JASDF绿',  nameEn:'JASDF Green',      hex:'#558b2f', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-74', name:'JASDF灰',  nameEn:'JASDF Grey',       hex:'#90a4ae', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-75', name:'IJN灰',    nameEn:'IJN Grey',         hex:'#9e9e9e', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-76', name:'IJN舰桥',  nameEn:'IJN Bridge',       hex:'#a0a080', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-77', name:'铁锈红',   nameEn:'Tire Black',       hex:'#3e2723', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-78', name:'木甲板',   nameEn:'Wooden Deck Tan',  hex:'#d7b899', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-79', name:'蓝灰色',   nameEn:'Blue Grey',        hex:'#78909c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-80', name:'皇家浅灰', nameEn:'Royal Light Grey', hex:'#b0bec5', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-81', name:'皇家浅蓝', nameEn:'Royal Light Blue', hex:'#90caf9', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-82', name:'海军蓝',   nameEn:'Ocean Grey',       hex:'#546e7a', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-83', name:'中海灰',   nameEn:'Medium Sea Grey',  hex:'#78909c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-84', name:'暗铁',     nameEn:'Dark Iron',        hex:'#424242', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-85', name:'橡胶黑',   nameEn:'Rubber Black',     hex:'#212121', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-86', name:'消光透明', nameEn:'Flat Clear',       hex:'#f0f8ff', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-87', name:'消光铝2',  nameEn:'Flat Aluminium',   hex:'#e0e0e0', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-88', name:'暗黄2',    nameEn:'Dark Yellow 2',    hex:'#c8a84b', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-89', name:'消光灰',   nameEn:'Flat Grey',        hex:'#9e9e9e', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-90', name:'消光白2',  nameEn:'White Grey',       hex:'#eceff1', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-91', name:'消光绿2',  nameEn:'Indochina Green',  hex:'#388e3c', type:'水性漆', finish:'flat' },
  { brand:'田宫 Tamiya', code:'XF-92', name:'消光黄绿', nameEn:'Yellow-green',     hex:'#aed581', type:'水性漆', finish:'flat' },

  // ─── Mr.Color C 系列（硝基漆）──────────────────────────────────────────────
  { brand:'Mr.Color', code:'C-1',  name:'白色',     nameEn:'White',          hex:'#f5f5f5', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-2',  name:'黑色',     nameEn:'Black',          hex:'#1a1a1a', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-3',  name:'红色',     nameEn:'Red',            hex:'#e53935', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-4',  name:'黄色',     nameEn:'Yellow',         hex:'#fdd835', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-5',  name:'蓝色',     nameEn:'Blue',           hex:'#1e88e5', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-6',  name:'绿色',     nameEn:'Green',          hex:'#43a047', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-7',  name:'棕色',     nameEn:'Brown',          hex:'#6d4c41', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-8',  name:'银色',     nameEn:'Silver',         hex:'#bdbdbd', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-9',  name:'金色',     nameEn:'Gold',           hex:'#d4a017', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-10', name:'铜色',     nameEn:'Copper',         hex:'#b87333', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-11', name:'橙色',     nameEn:'Orange',         hex:'#ef6c00', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-12', name:'浅蓝',     nameEn:'Light Blue',     hex:'#64b5f6', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-13', name:'暗绿',     nameEn:'Neutral Grey',   hex:'#2e7d32', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-14', name:'天蓝',     nameEn:'Sky Blue',       hex:'#81d4fa', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-15', name:'中间蓝',   nameEn:'Intermediate Blue', hex:'#1976d2', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-16', name:'黄橙',     nameEn:'Yellow Orange',  hex:'#ff9800', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-17', name:'RLM灰',    nameEn:'RLM 02 Grey',    hex:'#9e9e9e', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-18', name:'钢铁色',   nameEn:'Steel',          hex:'#607d8b', type:'硝基漆', finish:'semi'  },
  { brand:'Mr.Color', code:'C-19', name:'烟色',     nameEn:'Smoke',          hex:'#757575', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-20', name:'光亮漆',   nameEn:'Clear',          hex:'#f0f8ff', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-21', name:'中等灰',   nameEn:'Middle Stone',   hex:'#9e9e9e', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-22', name:'暗地球色', nameEn:'Dark Earth',     hex:'#795548', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-23', name:'浅绿',     nameEn:'Light Green',    hex:'#a5d6a7', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-27', name:'黑绿',     nameEn:'Black Green',    hex:'#1b5e20', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-28', name:'钢蓝',     nameEn:'Steel Blue',     hex:'#0d47a1', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-29', name:'海军蓝',   nameEn:'Navy Blue',      hex:'#0a1628', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-30', name:'暗棕',     nameEn:'Dark Brown',     hex:'#3e2723', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-32', name:'暗灰2',    nameEn:'Dark Grey 2',    hex:'#455a64', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-33', name:'消光黑',   nameEn:'Flat Black',     hex:'#212121', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-34', name:'消光白',   nameEn:'Flat White',     hex:'#f5f5f5', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-36', name:'消光红',   nameEn:'Flat Red',       hex:'#b71c1c', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-37', name:'RLM76',    nameEn:'RLM 76',         hex:'#cfd8dc', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-38', name:'RLM75',    nameEn:'RLM 75',         hex:'#78909c', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-39', name:'RLM74',    nameEn:'RLM 74',         hex:'#546e7a', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-40', name:'德军灰绿', nameEn:'German Grey Green', hex:'#4e6b4e', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-41', name:'红棕',     nameEn:'Red Brown',      hex:'#8d1c1c', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-43', name:'木色',     nameEn:'Wood Brown',     hex:'#d7b899', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-44', name:'沙黄',     nameEn:'Tan',            hex:'#c8a84b', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-45', name:'海军色',   nameEn:'Sail Color',     hex:'#ffe082', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-46', name:'橄榄绿',   nameEn:'Olive Green',    hex:'#689f38', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-47', name:'红棕2',    nameEn:'Warm Brown',     hex:'#a0522d', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-48', name:'舰桥灰',   nameEn:'Ship Grey',      hex:'#90a4ae', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-49', name:'暗海灰',   nameEn:'Dark Sea Grey',  hex:'#607d8b', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-50', name:'消光透明', nameEn:'Flat Clear',     hex:'#f0f8ff', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-51', name:'半光透明', nameEn:'Semi-Gloss Clear', hex:'#f0f8ff', type:'硝基漆', finish:'semi' },
  { brand:'Mr.Color', code:'C-52', name:'亮光透明', nameEn:'Gloss Clear',    hex:'#f0f8ff', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-53', name:'透明红',   nameEn:'Clear Red',      hex:'#ef9a9a', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-54', name:'透明蓝',   nameEn:'Clear Blue',     hex:'#90caf9', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-55', name:'透明绿',   nameEn:'Clear Green',    hex:'#a5d6a7', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-56', name:'透明橙',   nameEn:'Clear Orange',   hex:'#ffcc80', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-57', name:'透明黄',   nameEn:'Clear Yellow',   hex:'#fff176', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-58', name:'透明紫',   nameEn:'Clear Violet',   hex:'#ce93d8', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-59', name:'橙黄',     nameEn:'Orange Yellow',  hex:'#ffa726', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'C-60', name:'RLM02灰',  nameEn:'RLM 02',         hex:'#9e9e9e', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-61', name:'RLM65',    nameEn:'RLM 65',         hex:'#90caf9', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-62', name:'RLM66',    nameEn:'RLM 66',         hex:'#424242', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-63', name:'RLM70',    nameEn:'RLM 70',         hex:'#1b5e20', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-64', name:'RLM71',    nameEn:'RLM 71',         hex:'#2e7d32', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-65', name:'RLM72',    nameEn:'RLM 72',         hex:'#388e3c', type:'硝基漆', finish:'flat'  },
  { brand:'Mr.Color', code:'C-66', name:'RLM73',    nameEn:'RLM 73',         hex:'#43a047', type:'硝基漆', finish:'flat'  },

  // ─── 盖亚 Gaianotes（硝基漆）────────────────────────────────────────────────
  { brand:'盖亚 Gaianotes', code:'001',  name:'白色',     nameEn:'White',          hex:'#f5f5f5', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'002',  name:'黑色',     nameEn:'Black',          hex:'#1a1a1a', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'003',  name:'中灰',     nameEn:'Neutral Grey',   hex:'#9e9e9e', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'004',  name:'消光白',   nameEn:'Pure White',     hex:'#f5f5f5', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'005',  name:'消光黑',   nameEn:'Flat Black',     hex:'#212121', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'006',  name:'消光红',   nameEn:'Flat Red',       hex:'#c62828', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'007',  name:'消光蓝',   nameEn:'Flat Blue',      hex:'#1565c0', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'008',  name:'消光绿',   nameEn:'Flat Green',     hex:'#2e7d32', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'009',  name:'消光黄',   nameEn:'Flat Yellow',    hex:'#f9a825', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'010',  name:'消光橙',   nameEn:'Flat Orange',    hex:'#e65100', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'011',  name:'银色',     nameEn:'Silver',         hex:'#bdbdbd', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'012',  name:'金色',     nameEn:'Gold',           hex:'#d4a017', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'013',  name:'铜色',     nameEn:'Copper',         hex:'#b87333', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'014',  name:'钛银',     nameEn:'Star Bright Iron', hex:'#90a4ae', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'015',  name:'钛金',     nameEn:'Star Bright Gold', hex:'#d4a017', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'016',  name:'钛铜',     nameEn:'Star Bright Copper', hex:'#b87333', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'017',  name:'暗铁',     nameEn:'Dark Iron',      hex:'#546e7a', type:'硝基漆', finish:'semi'  },
  { brand:'盖亚 Gaianotes', code:'018',  name:'枪金属',   nameEn:'Gun Metal',      hex:'#607d8b', type:'硝基漆', finish:'semi'  },
  { brand:'盖亚 Gaianotes', code:'019',  name:'暗钢蓝',   nameEn:'Dark Steel Blue', hex:'#1a237e', type:'硝基漆', finish:'semi'  },
  { brand:'盖亚 Gaianotes', code:'020',  name:'纯白底漆', nameEn:'Surfacer White', hex:'#f5f5f5', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'021',  name:'灰底漆',   nameEn:'Surfacer Grey',  hex:'#9e9e9e', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'022',  name:'黑底漆',   nameEn:'Surfacer Black', hex:'#212121', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'023',  name:'钢铁色',   nameEn:'Stainless Steel', hex:'#eceff1', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'024',  name:'肤色',     nameEn:'Flesh',          hex:'#ffcc80', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'025',  name:'米白',     nameEn:'Cream Yellow',   hex:'#fff9c4', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'026',  name:'消光肤色', nameEn:'Flat Flesh',     hex:'#ffb74d', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'027',  name:'消光棕',   nameEn:'Flat Brown',     hex:'#795548', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'028',  name:'消光土',   nameEn:'Flat Earth',     hex:'#8d6e63', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'029',  name:'消光卡其', nameEn:'Flat Khaki',     hex:'#8d8741', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'030',  name:'消光灰',   nameEn:'Flat Grey',      hex:'#9e9e9e', type:'硝基漆', finish:'flat'  },

  // ─── 盖亚 GN 高达专用色系──────────────────────────────────────────────────
  { brand:'盖亚 Gaianotes', code:'GN-01', name:'MS白',   nameEn:'MS White',        hex:'#efefef', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-02', name:'MS暗灰', nameEn:'MS Dark Grey',    hex:'#546e7a', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-03', name:'MS深灰', nameEn:'MS Deep Grey',    hex:'#37474f', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-04', name:'MS关节灰', nameEn:'MS Joint Grey', hex:'#78909c', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-05', name:'MS浅蓝灰', nameEn:'MS Light Blue Grey', hex:'#b0bec5', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-06', name:'MS红',   nameEn:'MS Red',          hex:'#e53935', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-07', name:'MS暗红', nameEn:'MS Dark Red',     hex:'#b71c1c', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-08', name:'MS蓝',   nameEn:'MS Blue',         hex:'#1e88e5', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-09', name:'MS暗蓝', nameEn:'MS Dark Blue',    hex:'#0d47a1', type:'硝基漆', finish:'flat'  },
  { brand:'盖亚 Gaianotes', code:'GN-10', name:'MS黄',   nameEn:'MS Yellow',       hex:'#fdd835', type:'硝基漆', finish:'flat'  },

  // ─── Finisher's（硝基漆）────────────────────────────────────────────────────
  { brand:"Finisher's", code:'LF-1',  name:'超白',     nameEn:'Ultra White',    hex:'#ffffff', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-2',  name:'超黑',     nameEn:'Ultra Black',    hex:'#0d0d0d', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-3',  name:'白色底漆', nameEn:'Foundation White', hex:'#f5f5f5', type:'硝基漆', finish:'flat'  },
  { brand:"Finisher's", code:'LF-4',  name:'灰色底漆', nameEn:'Foundation Grey',  hex:'#9e9e9e', type:'硝基漆', finish:'flat'  },
  { brand:"Finisher's", code:'LF-5',  name:'金属黑',   nameEn:'Metallic Black', hex:'#212121', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-6',  name:'金属白',   nameEn:'Metallic White', hex:'#eceff1', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-7',  name:'银色',     nameEn:'Silver',         hex:'#e0e0e0', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-8',  name:'金色',     nameEn:'Gold',           hex:'#d4a017', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-9',  name:'铜色',     nameEn:'Bronze',         hex:'#b87333', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-10', name:'透明漆',   nameEn:'Pure Clear',     hex:'#f0f8ff', type:'硝基漆', finish:'gloss' },
  { brand:"Finisher's", code:'LF-11', name:'消光透明', nameEn:'Flat Clear',     hex:'#f0f8ff', type:'硝基漆', finish:'flat'  },
  { brand:"Finisher's", code:'LF-12', name:'半光透明', nameEn:'Semi-Gloss Clear', hex:'#f0f8ff', type:'硝基漆', finish:'semi' },

  // ─── 盖亚 EVO 补土系列（Surfacer / Primer）──────────────────────────────────
  { brand:'盖亚 Gaianotes', code:'EVO-01', name:'EVO白色补土',     nameEn:'EVO White Surfacer 1500', hex:'#f5f5f5', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-02', name:'EVO灰色补土',     nameEn:'EVO Grey Surfacer 1500',  hex:'#9e9e9e', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-03', name:'EVO黑色补土',     nameEn:'EVO Black Surfacer 1500', hex:'#212121', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-04', name:'EVO深灰补土',     nameEn:'EVO Dark Grey Surfacer',  hex:'#546e7a', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-05', name:'EVO浅灰补土',     nameEn:'EVO Light Grey Surfacer', hex:'#cfd8dc', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-06', name:'EVO粉红补土',     nameEn:'EVO Pink Surfacer',       hex:'#f8bbd0', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-07', name:'EVO橙色补土',     nameEn:'EVO Orange Surfacer',     hex:'#ffcc80', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-08', name:'EVO蓝色补土',     nameEn:'EVO Blue Surfacer',       hex:'#90caf9', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-09', name:'EVO黄色补土',     nameEn:'EVO Yellow Surfacer',     hex:'#fff176', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-10', name:'EVO红色补土',     nameEn:'EVO Red Surfacer',        hex:'#ef9a9a', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-11', name:'EVO绿色补土',     nameEn:'EVO Green Surfacer',      hex:'#a5d6a7', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-12', name:'EVO棕色补土',     nameEn:'EVO Brown Surfacer',      hex:'#bcaaa4', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-13', name:'EVO肤色补土',     nameEn:'EVO Flesh Surfacer',      hex:'#ffcc80', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-14', name:'EVO超白补土',     nameEn:'EVO Ultra White Surfacer',hex:'#ffffff', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-15', name:'EVO超黑补土',     nameEn:'EVO Ultra Black Surfacer',hex:'#0d0d0d', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-WH', name:'EVO多色白底补土', nameEn:'EVO Multi White',         hex:'#f5f5f5', type:'补土', finish:'flat' },
  { brand:'盖亚 Gaianotes', code:'EVO-BK', name:'EVO多色黑底补土', nameEn:'EVO Multi Black',         hex:'#212121', type:'补土', finish:'flat' },

  // ─── 盖亚 金属漆系列（Star Bright / Metal）────────────────────────────────
  { brand:'盖亚 Gaianotes', code:'SB-01', name:'超级银',         nameEn:'Star Bright Silver',       hex:'#e8e8e8', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-02', name:'超级金',         nameEn:'Star Bright Gold',         hex:'#d4a017', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-03', name:'超级铜',         nameEn:'Star Bright Copper',       hex:'#b87333', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-04', name:'超级铁',         nameEn:'Star Bright Iron',         hex:'#90a4ae', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-05', name:'超级钛金',       nameEn:'Star Bright Titanium Gold',hex:'#c9a84c', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-06', name:'超级钛银',       nameEn:'Star Bright Titanium Silver',hex:'#cfd8dc',type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-07', name:'超级枪金属',     nameEn:'Star Bright Duralumin',    hex:'#607d8b', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-08', name:'超级钢铁',       nameEn:'Star Bright Stainless',    hex:'#eceff1', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-09', name:'超级黑钢',       nameEn:'Star Bright Black Iron',   hex:'#37474f', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-10', name:'超级蓝金属',     nameEn:'Star Bright Blue',         hex:'#1565c0', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-11', name:'超级红金属',     nameEn:'Star Bright Red',          hex:'#c62828', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-12', name:'超级绿金属',     nameEn:'Star Bright Green',        hex:'#2e7d32', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-13', name:'超级紫金属',     nameEn:'Star Bright Purple',       hex:'#6a1b9a', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-14', name:'超级珍珠白',     nameEn:'Star Bright Pearl White',  hex:'#f0f4f8', type:'硝基漆', finish:'gloss' },
  { brand:'盖亚 Gaianotes', code:'SB-15', name:'超级极光金',     nameEn:'Star Bright Aurora Gold',  hex:'#ffe082', type:'硝基漆', finish:'gloss' },

  // ─── 郡士 Mr.Color CL 系列（透明色）────────────────────────────────────────
  { brand:'Mr.Color', code:'CL-1',  name:'透明黄',       nameEn:'Clear Yellow',        hex:'#fff176', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-2',  name:'透明橙',       nameEn:'Clear Orange',        hex:'#ffb74d', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-3',  name:'透明红',       nameEn:'Clear Red',           hex:'#ef9a9a', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-4',  name:'透明紫',       nameEn:'Clear Violet',        hex:'#ce93d8', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-5',  name:'透明蓝',       nameEn:'Clear Blue',          hex:'#90caf9', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-6',  name:'透明绿',       nameEn:'Clear Green',         hex:'#a5d6a7', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-7',  name:'透明黑烟',     nameEn:'Clear Smoke',         hex:'#546e7a', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-8',  name:'荧光粉红',     nameEn:'Fluorescent Pink',    hex:'#f48fb1', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-9',  name:'荧光橙',       nameEn:'Fluorescent Orange',  hex:'#ffcc02', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-10', name:'荧光黄',       nameEn:'Fluorescent Yellow',  hex:'#ffff00', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-11', name:'荧光绿',       nameEn:'Fluorescent Green',   hex:'#b9f6ca', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-12', name:'荧光蓝',       nameEn:'Fluorescent Blue',    hex:'#82b1ff', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-13', name:'荧光红',       nameEn:'Fluorescent Red',     hex:'#ff8a80', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-14', name:'透明橙黄',     nameEn:'Clear Yellow Orange', hex:'#ffa726', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-15', name:'透明粉红',     nameEn:'Clear Pink',          hex:'#f8bbd0', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-16', name:'透明浅蓝',     nameEn:'Clear Sky Blue',      hex:'#b3e5fc', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-17', name:'透明浅绿',     nameEn:'Clear Light Green',   hex:'#dcedc8', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-18', name:'透明蓝紫',     nameEn:'Clear Blue Violet',   hex:'#b39ddb', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-19', name:'透明棕',       nameEn:'Clear Brown',         hex:'#bcaaa4', type:'硝基漆', finish:'gloss' },
  { brand:'Mr.Color', code:'CL-20', name:'透明黑',       nameEn:'Clear Black',         hex:'#37474f', type:'硝基漆', finish:'gloss' },

];

// 搜索函数：按品牌/色号/颜色名/类型搜索
function searchPaintDB(query) {
  if (!query || query.trim().length < 1) return [];
  const q = query.toLowerCase().trim();
  return PAINT_DB.filter(p =>
    p.code.toLowerCase().includes(q) ||
    p.name.includes(q) ||
    p.nameEn.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q)
  ).filter(p => p.type !== '工具').slice(0, 40);
}
